#!/bin/bash
# SPDX-License-Identifier: MulanPSL-2.0+
# Copyright (c) 2020 Huawei Technologies Co., Ltd. All rights reserved.
# For your reference only.
# It's better to run the below scripts step by step.

[[ $CCI_SRC ]] || export CCI_SRC=$(cd $(dirname $(realpath $0)); git rev-parse --show-toplevel)
cd $CCI_SRC/sparrow || exit

echo "1-dependence for your os. runing this until all dependence installed"
echo "2-others brfor docker"
echo "3-build docker"
echo "4-others left"
echo "5-do all things at once(not necessary! another way besides 1-4)"
echo "others-not supported!"

read -n1 -p "input: " state
echo ""

case $state in
	1)
		source /etc/os-release
		echo "Install Dependence for: $ID"
		0-package/os/${ID}
		echo "If you see some error, reboot and do it again";;
	2)
		echo "Install folder 0 - 3"
		0-package/common
		. 0-package/read-config
		1-storage/tiny
		1-storage/permission
		2-network/br0
		2-network/br1
		2-network/iptables
		2-network/nfs
		2-network/cifs
		3-code/git
		3-code/dev-env;;
	3)
		echo "Build docker ... "
		path=/c/var/
		mkdir -p $path
		touch $path/out.log
		touch $path/err.log
		exec 1>$path/out.log
		exec 2>$path/err.log

		. 0-package/read-config
		. /etc/profile.d/compass.sh
		4-docker/buildall
		echo "dock build finished,but it may not work, check output up there";;
	4)
		echo "Do other things"
		. 0-package/read-config
		. /etc/profile.d/compass.sh
		5-build/ipxe
		5-build/os-ready
		5-build/register-account
		7-systemd/systemd-setup
		8-testbox/multi-docker
		8-testbox/multi-qemu
		echo "finished";;
	5)
		0-package/os/${ID}
		0-package/common
		. 0-package/read-config
		1-storage/tiny
		1-storage/permission
		2-network/br0
		2-network/br1
		2-network/iptables
		2-network/nfs
		2-network/cifs
		3-code/git
		3-code/dev-env
		. /etc/profile.d/compass.sh
		4-docker/buildall		
		5-build/ipxe
		5-build/os-ready
		5-build/register-account
		7-systemd/systemd-setup
		8-testbox/multi-docker
		8-testbox/multi-qemu;;
	*)
		echo "input not supported"
esac

